# Private Inputs
secret = ["1", "2", "3"]
salt = "0x6d696e68612d73616c74"

# Public Inputs (Devem ser o resultado real do c√°lculo acima)
guess = ["3", "2", "1"]
hash = "0x250476e2490ba30520aa558906ea14946f609151ad854f169d6e95f36bfcf566"
acertos = 1
permutados = 2
erros = 0
